# Generated by Django 4.2.7 on 2023-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data2',
            field=models.CharField(default='null', max_length=240, verbose_name='Data2'),
            preserve_default=False,
        ),
    ]
