# Generated by Django 4.2.7 on 2023-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_data_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='null', max_length=240, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
